version: '3.8'

services:
  ai-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
